.TH "BFH" 3 "Ср 25 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BFH \- 
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "unsigned short \fBbfType\fP"
.br
.ti -1c
.RI "unsigned int \fBbfSize\fP"
.br
.ti -1c
.RI "unsigned short \fBbfReserved1\fP"
.br
.ti -1c
.RI "unsigned short \fBbfReserved2\fP"
.br
.ti -1c
.RI "unsigned int \fBbfOffBits\fP"
.br
.in -1c
.SH "Данные класса"
.PP 
.SS "unsigned int BFH::bfOffBits"

.SS "unsigned short BFH::bfReserved1"

.SS "unsigned short BFH::bfReserved2"

.SS "unsigned int BFH::bfSize"

.SS "unsigned short BFH::bfType"


.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
