.TH "BIH" 3 "Ср 25 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BIH \- 
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "unsigned int \fBbiSize\fP"
.br
.ti -1c
.RI "int \fBbiWidth\fP"
.br
.ti -1c
.RI "int \fBbiHeight\fP"
.br
.ti -1c
.RI "unsigned short \fBbiPlanes\fP"
.br
.ti -1c
.RI "unsigned short \fBbiBitCount\fP"
.br
.ti -1c
.RI "unsigned int \fBbiCompression\fP"
.br
.ti -1c
.RI "unsigned int \fBbiSizeImage\fP"
.br
.ti -1c
.RI "int \fBbiXPelsPerMeter\fP"
.br
.ti -1c
.RI "int \fBbiYPelsPerMeter\fP"
.br
.ti -1c
.RI "unsigned int \fBbiClrUsed\fP"
.br
.ti -1c
.RI "unsigned int \fBbiClrImportant\fP"
.br
.in -1c
.SH "Данные класса"
.PP 
.SS "unsigned short BIH::biBitCount"

.SS "unsigned int BIH::biClrImportant"

.SS "unsigned int BIH::biClrUsed"

.SS "unsigned int BIH::biCompression"

.SS "int BIH::biHeight"

.SS "unsigned short BIH::biPlanes"

.SS "unsigned int BIH::biSize"

.SS "unsigned int BIH::biSizeImage"

.SS "int BIH::biWidth"

.SS "int BIH::biXPelsPerMeter"

.SS "int BIH::biYPelsPerMeter"


.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
