.TH "DialogNew" 3 "Вт 24 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogNew \- 
.PP
The \fBDialogNew\fP class Реализует диалоговое окно создания нового файла\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dialognew\&.h>\fP
.PP
Базовые классы:QDialog\&.
.SS "Сигналы"

.in +1c
.ti -1c
.RI "void \fBNewSize\fP (const QSize &size)"
.br
.in -1c
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBDialogNew\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetAreaWidth\fP (int width)"
.br
.ti -1c
.RI "void \fBsetAreaHeight\fP (int height)"
.br
.ti -1c
.RI "\fB~DialogNew\fP ()"
.br
.in -1c
.SS "Закрытые слоты"

.in +1c
.ti -1c
.RI "void \fBOkClicked\fP ()"
.br
.RI "\fI\fBDialogNew::OkClicked\fP Действие при нажатии на клавишу Ok\&. Запоминает размеры, установленные в полях Width и Height и отправляет на дальнейшую обработку с помощью NewSize\&. \fP"
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "Ui::DialogNew * \fBui\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
The \fBDialogNew\fP class Реализует диалоговое окно создания нового файла\&. 
.SH "Конструктор(ы)"
.PP 
.SS "DialogNew::DialogNew (QWidget *parent = \fC0\fP)\fC [explicit]\fP"

.SS "DialogNew::~DialogNew ()"

.SH "Методы"
.PP 
.SS "void DialogNew::NewSize (const QSize &size)\fC [signal]\fP"

.SS "void DialogNew::OkClicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
\fBDialogNew::OkClicked\fP Действие при нажатии на клавишу Ok\&. Запоминает размеры, установленные в полях Width и Height и отправляет на дальнейшую обработку с помощью NewSize\&. 
.SS "void DialogNew::setAreaHeight (intheight)"

.SS "void DialogNew::setAreaWidth (intwidth)"

.SH "Данные класса"
.PP 
.SS "Ui::DialogNew* DialogNew::ui\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
