.TH "dialogopen.cpp" 3 "Ср 25 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dialogopen.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'dialogopen\&.h'\fP
.br
\fC#include 'ui_dialogopen\&.h'\fP
.br
\fC#include <QPushButton>\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
