.TH "dialogopen.h" 3 "Вт 24 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dialogopen.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBDialogOpen\fP"
.br
.RI "\fIThe \fBDialogOpen\fP class Реализует диалоговое окно открытия файла\&. \fP"
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
