.TH "dialognew.cpp" 3 "Ср 25 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dialognew.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'dialognew\&.h'\fP
.br
\fC#include 'ui_dialognew\&.h'\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QSize>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include 'drawingarea\&.h'\fP
.br
\fC#include <QtWidgets>\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
