.TH "drawingarea.h" 3 "Вт 24 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drawingarea.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QColor>\fP
.br
\fC#include <QImage>\fP
.br
\fC#include <QPoint>\fP
.br
\fC#include <QSize>\fP
.br
\fC#include <QRect>\fP
.br
\fC#include <QBrush>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBDrawingArea\fP"
.br
.RI "\fIThe \fBDrawingArea\fP class Класс, относящийся к различного рода рисованию на полотне\&. \fP"
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
