.TH "mainwindow.cpp" 3 "Вт 24 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'drawingarea\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'ui_dialognew\&.h'\fP
.br
\fC#include 'dialognew\&.h'\fP
.br
\fC#include 'savefile\&.h'\fP
.br
\fC#include 'dialogopen\&.h'\fP
.br
\fC#include '2dgraph\&.cpp'\fP
.br
\fC#include <QtWidgets>\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QColorDialog>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QImageWriter>\fP
.br
\fC#include <QScrollArea>\fP
.br
\fC#include <QByteArray>\fP
.br

.SS "Переменные"

.in +1c
.ti -1c
.RI "QString \fBopenedFile\fP"
.br
.in -1c
.SH "Переменные"
.PP 
.SS "QString openedFile"

.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
