.TH "md__t_o_d_o" 3 "Вт 24 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__t_o_d_o \- TODO list 

.IP "1." 4
Задание размера полотна;
.IP "2." 4
Сохранение файла, открытие файла, сохранение в определенном формате\&.
.IP "3." 4
Рисование кривых отнести только к карандашу
.IP "4." 4
Реализовать функции:
.IP "  \(bu" 4
Заливка;
.IP "  \(bu" 4
Выделение области;
.IP "  \(bu" 4
Рисование прямоугольника/эллипса
.IP "  \(bu" 4
Ластик;
.IP "  \(bu" 4
Масштаб;
.PP

.IP "5." 4
Реализовать работу с выделенной областью; 
.PP

