.TH "md_design_project" 3 "Вт 24 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_design_project \- design project 
#Простой растровый графический редактор 
.SS "1\&. Наименование"
.PP
Простой растровый графический редактор “rAstro”
.PP
.SS "2\&. Назначение"
.PP
Назначение ПО – создание (и обработка?) растровых изображений, сохранение изображений в формате JPEG\&. ПО разрабатывается с целью получения навыков программирования и работы с проектами по разработке ПО\&.
.PP
.SS "3\&. Функции"
.PP
Общие функции:
.IP "\(bu" 2
Создание нового файла для растровых изображений;
.IP "\(bu" 2
Сохранение файла в любой момент времени в формате JPEG;
.IP "\(bu" 2
Открытие сохранённого файла для его изменения;
.IP "\(bu" 2
Вызов внешней пользовательской документации для изучения возможностей программы;
.PP
.PP
Функции обработки и создания изображений:
.IP "\(bu" 2
Рисование линий произвольной формы попиксельно – т\&.н\&. инструмент “карандаш”;
.IP "\(bu" 2
Изменение масштаба рисунка – то есть, с помощью инструмента масштабирования возможность приблизиться к некоторой области для того, чтобы лучше её рассмотреть; размер конечного полотна при этом не изменяется ;
.IP "\(bu" 2
Выделение области на рисунке – область выделяется прямоугольная, с помощью специального инструмента, путем зажатия левой клавиши мыши и проведением ей вдоль рисунка до получения нужного размера области;
.IP "\(bu" 2
Изменение масштаба/поворот/отражение выделенной области на рисунке – так же возможно вырезать эту область (то есть на рисунке её не будет, но она будет в буфере);
.IP "\(bu" 2
Копирование выделенной области на рисунке (помещение выделенной области в буфер);
.IP "\(bu" 2
Заливка области, ограниченной линией произвольной формы – таким образом можно выбирать фон для изображения – заливкой чистой области;
.IP "\(bu" 2
Рисование форм таких, как: прямоугольник, эллипс (возможно, многоугольники);
.IP "\(bu" 2
Выбор различных цветов из цветовой палитры, представляющей собой набор квадратиков основных цветов;
.IP "\(bu" 2
Функция удаления рисуемого изображения попиксельно (ластик);
.IP "\(bu" 2
Изменение размера рисуемых линий/границ прямоугольника и эллипса/ластика;
.IP "\(bu" 2
Возможность создания полотна для творчества любого размера (пикс х пикс)\&.
.PP
.PP
.SS "4\&. Интерфейс"
.PP
Интерфейс будет представлять собой окно, в верхней части которого распложены кнопки общих функций (Сохранить, открыть, создать, справка), под ними – полоса элементов, относящихся к рисованию (толщина карандаша/ластика, палитра, выбор формы рисования – кривая, эллипс или прямоугольник, инструмент заливки, инструмент выделения, инструмент “ластик”, группа инструментов, относящаяся к изменению выделенной области (масштаб, поворот, отражение, удалить область), инструмент “масштаб” представляющий собой выдвижное окошко с процентами от исходного размера области) В самом верхнем правом углу – кнопки “закрыть”, “свернуть”, “развернуть”\&. Ещё ниже будет область для рисования белого (стандартного для фона) цвета – размер области зависит от выбора при создании файла\&. Стандартный цвет для фона – белый, для инструментов рисования – чёрный\&. Управление будет происходить с помощью мыши, выбирая нужный инструмент и рисуя, зажав левую клавишу и проводя по рабочей области\&. 
