.TH "RGB_data" 3 "Вт 24 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RGB_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBb\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBg\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBr\fP"
.br
.in -1c
.SH "Данные класса"
.PP 
.SS "\fBBYTE\fP RGB_data::b"

.SS "\fBBYTE\fP RGB_data::g"

.SS "\fBBYTE\fP RGB_data::r"


.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
