.TH "tagBITMAPINFOHEADER" 3 "Вт 24 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagBITMAPINFOHEADER \- 
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "\fBDWORD\fP \fBbiSize\fP"
.br
.ti -1c
.RI "\fBLONG\fP \fBbiWidth\fP"
.br
.ti -1c
.RI "\fBLONG\fP \fBbiHeight\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBbiPlanes\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBbiBitCount\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBbiCompress\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBbiSizeImage\fP"
.br
.ti -1c
.RI "\fBLONG\fP \fBbiXPelsPerMeter\fP"
.br
.ti -1c
.RI "\fBLONG\fP \fBbiYPelsPerMeter\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBbiClrUsed\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBbiClrImportant\fP"
.br
.in -1c
.SH "Данные класса"
.PP 
.SS "\fBWORD\fP tagBITMAPINFOHEADER::biBitCount"

.SS "\fBDWORD\fP tagBITMAPINFOHEADER::biClrImportant"

.SS "\fBDWORD\fP tagBITMAPINFOHEADER::biClrUsed"

.SS "\fBDWORD\fP tagBITMAPINFOHEADER::biCompress"

.SS "\fBLONG\fP tagBITMAPINFOHEADER::biHeight"

.SS "\fBWORD\fP tagBITMAPINFOHEADER::biPlanes"

.SS "\fBDWORD\fP tagBITMAPINFOHEADER::biSize"

.SS "\fBDWORD\fP tagBITMAPINFOHEADER::biSizeImage"

.SS "\fBLONG\fP tagBITMAPINFOHEADER::biWidth"

.SS "\fBLONG\fP tagBITMAPINFOHEADER::biXPelsPerMeter"

.SS "\fBLONG\fP tagBITMAPINFOHEADER::biYPelsPerMeter"


.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
