.TH "tagBITMAPFILEHEADER" 3 "Вт 24 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagBITMAPFILEHEADER \- 
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "\fBWORD\fP \fBbfType\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBbfSize\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBbfReserved1\fP"
.br
.ti -1c
.RI "\fBWORD\fP \fBbfReserved2\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBbfOffBits\fP"
.br
.in -1c
.SH "Данные класса"
.PP 
.SS "\fBDWORD\fP tagBITMAPFILEHEADER::bfOffBits"

.SS "\fBWORD\fP tagBITMAPFILEHEADER::bfReserved1"

.SS "\fBWORD\fP tagBITMAPFILEHEADER::bfReserved2"

.SS "\fBDWORD\fP tagBITMAPFILEHEADER::bfSize"

.SS "\fBWORD\fP tagBITMAPFILEHEADER::bfType"


.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
