.TH "tagRGBTRIPLE" 3 "Ср 25 Май 2016" "Version 0.5" "rAstro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagRGBTRIPLE \- 
.SH SYNOPSIS
.br
.PP
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBrgbtBlue\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBrgbtGreen\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBrgbtRed\fP"
.br
.in -1c
.SH "Данные класса"
.PP 
.SS "\fBBYTE\fP tagRGBTRIPLE::rgbtBlue"

.SS "\fBBYTE\fP tagRGBTRIPLE::rgbtGreen"

.SS "\fBBYTE\fP tagRGBTRIPLE::rgbtRed"


.SH "Автор"
.PP 
Автоматически создано Doxygen для rAstro из исходного текста\&.
